version: '3'
services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi
