name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest

      - name: deploy application
        run: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d --name fastapi-app -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest


    #   - name: Deploy to Server
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SERVER_HOST }}
    #       username: ${{ secrets.SERVER_USER }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest
    #         docker stop fastapi-app || true
    #         docker rm fastapi-app || true
    #         docker run -d --name fastapi-app -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest



                

